import sgMail from "@sendgrid/mail";

// Sends a personalised email to each participant individually
export async function sendMeetingBrief({ participants, meetingType, meetingDate, meetingTime, project, prep }) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);

  const {
    summary = "",
    preparation_points = [],
    agenda_suggestions = [],
    follow_ups = [],
    key_risks = [],
  } = prep;

  const li = items => items.map(i => `<li style="margin-bottom:6px">${i}</li>`).join("");

  const followUpRows = follow_ups.map(f => {
    if (typeof f === "string") return `<li style="margin-bottom:6px">${f}</li>`;
    const item     = f.item || f.action || "";
    const owner    = f.owner    ? ` <span style="color:#b45309">— ${f.owner}</span>` : "";
    const deadline = f.deadline ? ` <span style="color:#6b7280;font-size:12px">(Due: ${f.deadline})</span>` : "";
    return `<li style="margin-bottom:6px">${item}${owner}${deadline}</li>`;
  }).join("");

  const section = (emoji, title, content) =>
    `<div style="margin-bottom:22px">
      <h3 style="margin:0 0 8px;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#1e40af">${emoji} ${title}</h3>
      ${content}
    </div>`;

  const buildHtml = (name) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:'Segoe UI',Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f1f5f9;padding:32px 0">
  <tr><td align="center">
  <table width="620" cellpadding="0" cellspacing="0" border="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden">

    <!-- Header -->
    <tr>
      <td bgcolor="#1e3a8a" style="background-color:#1e3a8a;padding:28px 32px">
        <p style="margin:0 0 4px;font-size:12px;color:#93c5fd;text-transform:uppercase;letter-spacing:0.06em;font-family:'Segoe UI',Arial,sans-serif">Meeting Brief</p>
        <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#ffffff;font-family:'Segoe UI',Arial,sans-serif">${meetingType}</h1>
        <p style="margin:0;font-size:13px;color:#bfdbfe;font-family:'Segoe UI',Arial,sans-serif">${project} &nbsp;&middot;&nbsp; ${meetingDate} &nbsp;&middot;&nbsp; ${meetingTime}</p>
        <p style="margin:4px 0 0;font-size:11px;color:#93c5fd;font-family:'Segoe UI',Arial,sans-serif">This brief was sent 15 minutes before the meeting</p>
      </td>
    </tr>

    <!-- Greeting -->
    <tr>
      <td style="padding:28px 32px 8px;font-family:'Segoe UI',Arial,sans-serif">
        <p style="margin:0;font-size:15px;color:#111827;line-height:1.6">Hi <strong>${name}</strong>,<br/>Here is your meeting brief to help you prepare for the upcoming <strong>${meetingType}</strong> on <strong>${meetingDate}</strong> at <strong>${meetingTime}</strong>.</p>
      </td>
    </tr>

    <!-- Content -->
    <tr>
      <td style="padding:12px 32px 24px;font-family:'Segoe UI',Arial,sans-serif;font-size:14px;color:#374151;line-height:1.65">
        ${summary ? section("📋", "Status Summary", `<p style="margin:0;color:#374151">${summary}</p>`) : ""}
        ${agenda_suggestions.length ? section("📌", "Agenda for Today's Meeting", `<ol style="margin:0;padding-left:20px;color:#374151">${li(agenda_suggestions)}</ol>`) : ""}
        ${preparation_points.length ? section("✅", "Preparation Points", `<ul style="margin:0;padding-left:20px;color:#374151">${li(preparation_points)}</ul>`) : ""}
        ${follow_ups.length ? section("🔁", "Open Follow-ups", `<ul style="margin:0;padding-left:20px;color:#374151">${followUpRows}</ul>`) : ""}
        ${key_risks.length ? section("⚠️", "Key Risks / Blockers", `<ul style="margin:0;padding-left:20px;color:#374151">${li(key_risks)}</ul>`) : ""}
      </td>
    </tr>

    <!-- Footer -->
    <tr>
      <td bgcolor="#f8fafc" style="background-color:#f8fafc;padding:14px 32px;text-align:center;font-size:12px;color:#94a3b8;border-top:1px solid #e2e8f0;font-family:'Segoe UI',Arial,sans-serif">
        Generated by Office Meeting Prep Agent &nbsp;&middot;&nbsp; Azure OpenAI
      </td>
    </tr>

  </table>
  </td></tr>
</table>
</body>
</html>`;

  // Send one personalised email per participant
  const sends = participants.map(({ name, email }) =>
    sgMail.send({
      to: email,
      from: process.env.SENDGRID_FROM,
      subject: `📋 Meeting Brief: ${meetingType} — ${meetingDate} at ${meetingTime}`,
      html: buildHtml(name),
    })
  );

  return Promise.all(sends);
}
